plugins {
    id("multiloader-common")
    alias(libs.plugins.mdg)
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file("src/main/resources/META-INF/accesstransformer_xplat.cfg")
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly(libs.bundles.mixin)
    annotationProcessor(libs.mixin.extras)

    compileOnly(libs.patchouli.xplat)
    compileOnly(libs.ears)
    compileOnly(libs.jei.common.api)
    compileOnly(variantOf(libs.emi.xplat) { classifier("api") })
    compileOnly(libs.rei.neoforge) // (the -common variant would be in Intermediary mapping)

    compileOnly(libs.jetbrains.annotations)
}

tasks.register("normalizeLanguageFiles", JavaExec) {
    group = "verification"
    description = "Normalize language file layout according to en_us.json"
    classpath = sourceSets.main.runtimeClasspath
    mainClass = "vazkii.botania.data.LangSortTool"
    workingDir = projectDir.parent
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava(sourceSets.main.java.sourceDirectories.singleFile)
    commonResources(sourceSets.main.resources.sourceDirectories.files)
}
