github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: "Vazkii" # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
liberapay: "williewillus" # Replace with a single Liberapay username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
