plugins {
    id("idea")
    alias(libs.plugins.spotless) apply false
}

println("Java: ${System.getProperty("java.version")}, JVM: ${System.getProperty("java.vm.version")} (${System.getProperty("java.vendor")}), Arch: ${System.getProperty("os.arch")}")

idea.module {
    downloadJavadoc = true
    downloadSources = true
}
