# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
build_number=455
group=vazkii.botania
java_version=21

# Xplat
minecraft_version=1.21.1
mod_name=Botania
mod_author=Vazkii
mod_id=botania
license=Botania license
description=Botania is a tech mod themed around natural magic
website_url=https://botaniamod.net
sources_url=https://github.com/VazkiiMods/Botania
issue_url=https://github.com/Vazkii/Botania/issues
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_version=2024.11.17

# Keep this synchronized with garden_of_glass/Makefile:
gog_version=14

# Uncomment to load the specified recipe viewer (instead of the default one)
#load_override_emi=true
#load_override_jei=true
#load_override_rei=true

#load_fabric_carpet=true
#load_fabric_speedrunigt=true

# Fabric
fabric_version=0.116.12+1.21.1
fabric_loader_version=0.17.3

# NeoForge
neoforge_version=21.1.229
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.warning.mode=all
