pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = "Fabric"
            url = uri("https://maven.fabricmc.net")
        }
        maven {
            name = "NeoForged"
            url = "https://maven.neoforged.net/releases"
            content {
                includeGroup("net.neoforged")
            }
        }
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "Botania"
includeBuild("build-logic")
include("Xplat")
include("Fabric")
include("NeoForge")
