<div class='section-header'>
	<span class='glyphicon glyphicon-comment'></span>
	Botania FAQ
</div>

<ul>

<li id="q1-fake"><b>Can I use Botania in a modpack, let's play, or its code in my mod?</b> <a href="#q1">(permalink)</a><br>
Have a look through the <a href="http://botaniamod.net/license.php">license</a> section of the website.</li><br>

<li id="q2-fake"><b>Is Botania opensource?</b> <a href="#q2">(permalink)</a><br>
Yes, <a href="https://github.com/Vazkii/Botania">yes it is</a>.</li><br>

<li id="q3-fake"><b>When is the mod getting updated to 1.x?</b> <a href="#q3">(permalink)</a><br>
It's ready when it's ready. Please don't bicker about it over email, twitter or what have you all the time, it doesn't help.</li><br>

<li id="q4-fake"><b>How can I contact you?</b> <a href="#q4">(permalink)</a><br>
Check the <a href="http://vazkii.us/about-me/contact/">contact</a> section on my website. Please read this entire FAQ before you do. Please. Just... please.</li><br>

<li id="q5-fake"><b>Can the flowers in this mod be retroactively generated?</b> <a href="#q5">(permalink)</a><br>
No, they can't, due to the method they use for generation. They're generated during biome decoration, so the amount of flowers depends on how many flowers would be in that biome to begin with. You can still get the mod's flowers easilly through creating Floral Fertilizer, which is a pretty early game item.</li><br>

<li id="q6-fake"><b>There's too many flowers! How do I lower the amount?</b> <a href="#q6">(permalink)</a><br>
As of the latest versions, the amount of flowers generated by default has been drastically lowered. If you still want to, though, you can lower the frequency (how often they spawn) and the density (how many spawn at once for each "patch") in the config.</li><br>

<li id="q7-fake"><b>My flowers disappeared or turned into dead bushes! What gives?</b> <a href="#q7">(permalink)</a><br>
As of recently, passive flower decay has been enabled by default and the config option for it has been removed. (you can read more about that <a href="http://vazkii.us/uncategorized/sins-of-a-solar-empire-or-the-passive-generation-conundrum/">here</a>). This cause any passive flowers to decay and turn into Dead Bushes after a while. This is normal, and you should consider upgrading to better flowers that won't do that.</li><br>

<li id="q8-fake"><b>Could you add a config option to restrict flowers to specific biomes?</b> <a href="#q8">(permalink)</a><br>
Given that each flower is required for the progression, no, this seems like a terrible idea. I have no interest in doing this.<br></li><br>

<li id="q9-fake"><b>My Mana Pool's Mana isn't changing, I got a few flowers producing and the bar doesn't move, what's wrong?</b> <a href="#q9">(permalink)</a><br>
The Mana Pool holds a lot of mana. Flowers like Hydroangeas produce a very little amount of it, so you probably won't even notice the difference in the bar. Go get some better flowers like Endoflames.</li><br>

<li id="q10-fake"><b>I found a bug, how do I report it?</b> <a href="#q10">(permalink)</a><br>
I made a <a href="http://vazkii.us/br101/">website</a> to teach people how to report bugs, read what's on there and then go report it on the <a href="https://github.com/Vazkii/Botania/issues">issue tracker</a>.</li><br>

<li id="q11-fake"><b>I have a suggestion for botania. Where do I put it?</b> <a href="#q11">(permalink)</a><br>
The best place for suggestions is the <a href="https://www.reddit.com/r/botania">/r/botania</a> subreddit. Before you do, however, please read <a href="http://vazkii.us/uncategorized/stuff-you-wont-see-in-botania/">this blog post</a>, so you don't suggest something that I've denied countless times already.</li><br>

<li id="q12-fake"><b>My console is getting spammed with "true" or "false" in the 1.6 version. How do I fix that?</b> <a href="#q12">(permalink)</a><br>
I accidentally a debug in, I fixed it in 1.7, if you don't want to update, don't place down Nightshades.<br></li><br>

<li id="q13-fake"><b>My game has been very laggy since I installed botania, how can I fix it?</b> <a href="#q13">(permalink)</a><br>
First off, make sure you are on the latest version, there have been lots of optimization patches, if you're still lagging, go check the mod's config. Try turning off the shaders, if that doesn't help, try setting the flower particle frequency to 0. If that doesn't do it either then I really don't know what will.</li><br>

<li id="q14-fake"><b>Is the Terra Blade from Terraria?</b> <a href="#q14">(permalink)</a><br>
<a href="http://vazkii.us/mod/Botania/terrablade.html">http://vazkii.us/mod/Botania/terrablade.html</a></li><br>

<li id="q15-fake"><b>Is there a Botania API? Can I make a Botania Addon?</b> <a href="#q15">(permalink)</a><br>
Yes, there is <a href="https://github.com/Vazkii/Botania/tree/master/src/main/java/vazkii/botania/api">an API</a>. When it comes to making addons, you can make them, but please give me a poke about what you're going to add. I hold no ability to disallow you to add some things, given the mod's license, but I at least like to know what's being done. It's not required though.</li><br>

<li id="q15-fake"><b>What is the airspeed velocity of an unladen swallow?</b> <a href="#q16">(permalink)</a><br>
African or European?</li>

</ul>
