/**
 * This class was created by <Vazkii>. It's distributed as
 * part of the Botania Mod. Get the Source Code in github:
 * https://github.com/Vazkii/Botania
 *
 * Botania is Open Source and distributed under the
 * Botania License: http://botaniamod.net/license.php
 *
 * File Created @ [Jan 14, 2014, 5:17:47 PM (GMT)]
 */
package vazkii.botania.common.item;

import net.minecraft.init.Items;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.EnumDyeColor;
import net.minecraft.item.Item;
import net.minecraft.item.ItemRecord;
import net.minecraft.item.ItemStack;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.oredict.OreDictionary;
import net.minecraftforge.registries.IForgeRegistry;
import vazkii.botania.api.BotaniaAPI;
import vazkii.botania.api.item.IFloatingFlower;
import vazkii.botania.api.mana.spark.SparkUpgradeType;
import vazkii.botania.api.item.IAncientWillContainer;
import vazkii.botania.api.state.enums.CratePattern;
import vazkii.botania.common.block.ModBlocks;
import vazkii.botania.common.core.BotaniaCreativeTab;
import vazkii.botania.common.core.handler.ModSounds;
import vazkii.botania.common.item.brew.*;
import vazkii.botania.common.item.equipment.armor.elementium.ItemElementiumBoots;
import vazkii.botania.common.item.equipment.armor.elementium.ItemElementiumChest;
import vazkii.botania.common.item.equipment.armor.elementium.ItemElementiumHelm;
import vazkii.botania.common.item.equipment.armor.elementium.ItemElementiumLegs;
import vazkii.botania.common.item.equipment.armor.manasteel.ItemManasteelArmor;
import vazkii.botania.common.item.equipment.armor.manasteel.ItemManasteelBoots;
import vazkii.botania.common.item.equipment.armor.manasteel.ItemManasteelChest;
import vazkii.botania.common.item.equipment.armor.manasteel.ItemManasteelHelm;
import vazkii.botania.common.item.equipment.armor.manasteel.ItemManasteelLegs;
import vazkii.botania.common.item.equipment.armor.manaweave.ItemManaweaveArmor;
import vazkii.botania.common.item.equipment.armor.manaweave.ItemManaweaveBoots;
import vazkii.botania.common.item.equipment.armor.manaweave.ItemManaweaveChest;
import vazkii.botania.common.item.equipment.armor.manaweave.ItemManaweaveHelm;
import vazkii.botania.common.item.equipment.armor.manaweave.ItemManaweaveLegs;
import vazkii.botania.common.item.equipment.armor.terrasteel.ItemTerrasteelArmor;
import vazkii.botania.common.item.equipment.armor.terrasteel.ItemTerrasteelBoots;
import vazkii.botania.common.item.equipment.armor.terrasteel.ItemTerrasteelChest;
import vazkii.botania.common.item.equipment.armor.terrasteel.ItemTerrasteelHelm;
import vazkii.botania.common.item.equipment.armor.terrasteel.ItemTerrasteelLegs;
import vazkii.botania.common.item.equipment.bauble.*;
import vazkii.botania.common.item.equipment.tool.ItemEnderDagger;
import vazkii.botania.common.item.equipment.tool.ItemGlassPick;
import vazkii.botania.common.item.equipment.tool.ItemStarSword;
import vazkii.botania.common.item.equipment.tool.ItemThunderSword;
import vazkii.botania.common.item.equipment.tool.bow.ItemCrystalBow;
import vazkii.botania.common.item.equipment.tool.bow.ItemLivingwoodBow;
import vazkii.botania.common.item.equipment.tool.elementium.ItemElementiumAxe;
import vazkii.botania.common.item.equipment.tool.elementium.ItemElementiumPick;
import vazkii.botania.common.item.equipment.tool.elementium.ItemElementiumShears;
import vazkii.botania.common.item.equipment.tool.elementium.ItemElementiumShovel;
import vazkii.botania.common.item.equipment.tool.elementium.ItemElementiumSword;
import vazkii.botania.common.item.equipment.tool.manasteel.ItemManasteelAxe;
import vazkii.botania.common.item.equipment.tool.manasteel.ItemManasteelPick;
import vazkii.botania.common.item.equipment.tool.manasteel.ItemManasteelShears;
import vazkii.botania.common.item.equipment.tool.manasteel.ItemManasteelShovel;
import vazkii.botania.common.item.equipment.tool.manasteel.ItemManasteelSword;
import vazkii.botania.common.item.equipment.tool.terrasteel.ItemTerraAxe;
import vazkii.botania.common.item.equipment.tool.terrasteel.ItemTerraPick;
import vazkii.botania.common.item.equipment.tool.terrasteel.ItemTerraSword;
import vazkii.botania.common.item.interaction.thaumcraft.ItemElementiumHelmRevealing;
import vazkii.botania.common.item.interaction.thaumcraft.ItemManaInkwell;
import vazkii.botania.common.item.interaction.thaumcraft.ItemManasteelHelmRevealing;
import vazkii.botania.common.item.interaction.thaumcraft.ItemTerrasteelHelmRevealing;
import vazkii.botania.common.item.lens.*;
import vazkii.botania.common.item.material.ItemDye;
import vazkii.botania.common.item.material.ItemEnderAir;
import vazkii.botania.common.item.material.ItemManaResource;
import vazkii.botania.common.item.material.ItemPestleAndMortar;
import vazkii.botania.common.item.material.ItemPetal;
import vazkii.botania.common.item.material.ItemRune;
import vazkii.botania.common.item.record.ItemModRecord;
import vazkii.botania.common.item.relic.ItemDice;
import vazkii.botania.common.item.relic.ItemFlugelEye;
import vazkii.botania.common.item.relic.ItemInfiniteFruit;
import vazkii.botania.common.item.relic.ItemKingKey;
import vazkii.botania.common.item.relic.ItemLokiRing;
import vazkii.botania.common.item.relic.ItemOdinRing;
import vazkii.botania.common.item.relic.ItemThorRing;
import vazkii.botania.common.item.rod.ItemCobbleRod;
import vazkii.botania.common.item.rod.ItemDirtRod;
import vazkii.botania.common.item.rod.ItemDiviningRod;
import vazkii.botania.common.item.rod.ItemExchangeRod;
import vazkii.botania.common.item.rod.ItemFireRod;
import vazkii.botania.common.item.rod.ItemGravityRod;
import vazkii.botania.common.item.rod.ItemMissileRod;
import vazkii.botania.common.item.rod.ItemRainbowRod;
import vazkii.botania.common.item.rod.ItemSkyDirtRod;
import vazkii.botania.common.item.rod.ItemSmeltRod;
import vazkii.botania.common.item.rod.ItemTerraformRod;
import vazkii.botania.common.item.rod.ItemTornadoRod;
import vazkii.botania.common.item.rod.ItemWaterRod;
import vazkii.botania.common.lib.LibItemNames;
import vazkii.botania.common.lib.LibMisc;
import vazkii.botania.common.lib.LibOreDict;

import java.util.*;
import java.util.stream.Collectors;

@Mod.EventBusSubscriber(modid = LibMisc.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
public final class ModItems {
	public static final Item lexicon = new ItemLexicon(unstackable());
	public static final Map<EnumDyeColor, Item> petals = new EnumMap<>(EnumDyeColor.class);
	public static final Map<EnumDyeColor, Item> dyes = new EnumMap<>(EnumDyeColor.class);
	static {
		for(EnumDyeColor color : EnumDyeColor.values()) {
			petals.put(color, new ItemPetal(ModBlocks.getBuriedPetal(color), color, defaultBuilder()));
			dyes.put(color, new ItemDye(color, defaultBuilder()));
		}
	}

	public static final Item pestleAndMortar = new ItemPestleAndMortar(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.PESTLE_AND_MORTAR);
	public static final Item twigWand = new ItemTwigWand(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TWIG_WAND);
	
	public static final Item manaSteel = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[0]);
	public static final Item manaPearl = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[1]);
	public static final Item manaDiamond = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[2]);
	public static final Item livingwoodTwig = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[3]);
	public static final Item terrasteel = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[4]);
	public static final Item lifeEssence = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[5]);
	public static final Item redstoneRoot = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[6]);
	public static final Item elementium = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[7]);
	public static final Item pixieDust = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[8]);
	public static final Item dragonstone = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[9]);
	public static final Item placeholder = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[11]);
	public static final Item redString = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[12]);
	public static final Item dreamwoodTwig = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[13]);
	public static final Item gaiaIngot = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[14]);
	public static final Item enderAirBottle = new ItemEnderAir(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[15]);
	public static final Item manaString = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[16]);
	public static final Item manasteelNugget = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[17]);
	public static final Item terrasteelNugget = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[18]);
	public static final Item elementiumNugget = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[19]);
	public static final Item livingroot = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[20]);
	public static final Item pebble = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[21]);
	public static final Item manaweaveCloth = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[22]);
	public static final Item manaPowder = new ItemManaResource(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RESOURCE_NAMES[23]);
	
	public static final Item lensNormal = new ItemLens(unstackable(), new Lens(), ItemLens.PROP_NONE).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[0]);
	public static final Item lensSpeed = new ItemLens(unstackable(), new LensSpeed(), ItemLens.PROP_NONE).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[1]);
	public static final Item lensPower = new ItemLens(unstackable(), new LensPower(), ItemLens.PROP_POWER).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[2]);
	public static final Item lensTime = new ItemLens(unstackable(), new LensTime(), ItemLens.PROP_NONE).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[3]);
	public static final Item lensEfficiency = new ItemLens(unstackable(), new LensEfficiency(), ItemLens.PROP_NONE).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[4]);
	public static final Item lensBounce = new ItemLens(unstackable(), new LensBounce(), ItemLens.PROP_TOUCH).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[5]);
	public static final Item lensGravity = new ItemLens(unstackable(), new LensGravity(), ItemLens.PROP_ORIENTATION).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[6]);
	public static final Item lensMine = new ItemLens(unstackable(), new LensMine(), ItemLens.PROP_TOUCH | ItemLens.PROP_ORIENTATION).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[7]);
	public static final Item lensDamage = new ItemLens(unstackable(), new LensDamage(), ItemLens.PROP_DAMAGE).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[8]);
	public static final Item lensPhantom = new ItemLens(unstackable(), new LensPhantom(), ItemLens.PROP_TOUCH).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[9]);
	public static final Item lensMagnet = new ItemLens(unstackable(), new LensMagnet(), ItemLens.PROP_ORIENTATION).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[10]);
	public static final Item lensExplosive = new ItemLens(unstackable(), new LensExplosive(), ItemLens.PROP_DAMAGE | ItemLens.PROP_TOUCH | ItemLens.PROP_INTERACTION).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[11]);
	public static final Item lensInfluence = new ItemLens(unstackable(), new LensInfluence(), ItemLens.PROP_NONE).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[12]);
	public static final Item lensWeight = new ItemLens(unstackable(), new LensWeight(), ItemLens.PROP_TOUCH | ItemLens.PROP_INTERACTION).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[13]);
	public static final Item lensPaint = new ItemLens(unstackable(), new LensPaint(), ItemLens.PROP_TOUCH | ItemLens.PROP_INTERACTION).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[14]);
	public static final Item lensFire = new ItemLens(unstackable(), new LensFire(), ItemLens.PROP_DAMAGE | ItemLens.PROP_TOUCH | ItemLens.PROP_INTERACTION).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[15]);
	public static final Item lensPiston = new ItemLens(unstackable(), new LensPiston(), ItemLens.PROP_TOUCH | ItemLens.PROP_INTERACTION).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[16]);
	public static final Item lensLight = new ItemLens(unstackable(), new LensLight(), ItemLens.PROP_TOUCH | ItemLens.PROP_INTERACTION).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[17]);
	public static final Item lensWarp = new ItemLens(unstackable(), new LensWarp(), ItemLens.PROP_NONE).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[18]);
	public static final Item lensRedirect = new ItemLens(unstackable(), new LensRedirect(), ItemLens.PROP_TOUCH | ItemLens.PROP_INTERACTION).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[19]);
	public static final Item lensFirework = new ItemLens(unstackable(), new LensFirework(), ItemLens.PROP_TOUCH).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[20]);
	public static final Item lensFlare = new ItemLens(unstackable(), new LensFlare(), ItemLens.PROP_CONTROL).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[21]);
	public static final Item lensMessenger = new ItemLens(unstackable(), new LensMessenger(), ItemLens.PROP_POWER).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[22]);
	public static final Item lensTripwire = new ItemLens(unstackable(), new LensTripwire(), ItemLens.PROP_CONTROL).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[23]);
	public static final Item lensStorm = new ItemLens(unstackable(), new LensStorm(), ItemLens.PROP_NONE).setRegistryName(LibMisc.MOD_ID, LibItemNames.LENS_NAMES[24]);
	
	public static final Item runeWater = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[0]);
	public static final Item runeFire = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[1]);
	public static final Item runeEarth = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[2]);
	public static final Item runeAir = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[3]);
	public static final Item runeSpring = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[4]);
	public static final Item runeSummer = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[5]);
	public static final Item runeAutumn = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[6]);
	public static final Item runeWinter = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[7]);
	public static final Item runeMana = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[8]);
	public static final Item runeLust = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[9]);
	public static final Item runeGluttony = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[10]);
	public static final Item runeGreed = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[11]);
	public static final Item runeSloth = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[12]);
	public static final Item runeWrath = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[13]);
	public static final Item runeEnvy = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[14]);
	public static final Item runePride = new ItemRune(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RUNE_NAMES[15]);

	public static final Item manaTablet = new ItemManaTablet(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_TABLET);
	public static final Item manaGun = new ItemManaGun(unstackable().setNoRepair()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_GUN);
	public static final Item manaCookie = new ItemManaCookie(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_COOKIE);
	public static final Item fertilizer = new ItemFertilizer(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.FERTILIZER);

	public static final Item grassSeeds = new ItemGrassSeeds(IFloatingFlower.IslandType.GRASS, defaultBuilder());
	public static final Item podzolSeeds = new ItemGrassSeeds(IFloatingFlower.IslandType.PODZOL, defaultBuilder());
	public static final Item mycelSeeds = new ItemGrassSeeds(IFloatingFlower.IslandType.MYCEL, defaultBuilder());
	public static final Item drySeeds = new ItemGrassSeeds(IFloatingFlower.IslandType.DRY, defaultBuilder());
	public static final Item goldenSeeds = new ItemGrassSeeds(IFloatingFlower.IslandType.GOLDEN, defaultBuilder());
	public static final Item vividSeeds = new ItemGrassSeeds(IFloatingFlower.IslandType.VIVID, defaultBuilder());
	public static final Item scorchedSeeds = new ItemGrassSeeds(IFloatingFlower.IslandType.SCORCHED, defaultBuilder());
	public static final Item infusedSeeds = new ItemGrassSeeds(IFloatingFlower.IslandType.INFUSED, defaultBuilder());
	public static final Item mutatedSeeds = new ItemGrassSeeds(IFloatingFlower.IslandType.MUTATED, defaultBuilder());

	public static final Item dirtRod = new ItemDirtRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.DIRT_ROD);
	public static final Item terraformRod = new ItemTerraformRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TERRAFORM_ROD);
	public static final Item grassHorn = new ItemHorn(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.GRASS_HORN);
	public static final Item leavesHorn = new ItemHorn(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.LEAVES_HORN);
	public static final Item snowHorn = new ItemHorn(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SNOW_HORN);
	public static final Item manaMirror = new ItemManaMirror(unstackable().defaultMaxDamage(1000).setNoRepair()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_MIRROR);
	public static final Item manasteelHelm = new ItemManasteelHelm(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANASTEEL_HELM);
	public static final Item manasteelHelmRevealing = new ItemManasteelHelmRevealing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANASTEEL_HELM_R);
	public static final Item manasteelChest = new ItemManasteelArmor(EntityEquipmentSlot.CHEST, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANASTEEL_CHEST);
	public static final Item manasteelLegs = new ItemManasteelArmor(EntityEquipmentSlot.LEGS, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANASTEEL_LEGS);
	public static final Item manasteelBoots = new ItemManasteelArmor(EntityEquipmentSlot.FEET, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANASTEEL_BOOTS);
	public static final Item manasteelPick = new ItemManasteelPick(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANASTEEL_PICK);
	public static final Item manasteelShovel = new ItemManasteelShovel(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANASTEEL_SHOVEL);
	public static final Item manasteelAxe = new ItemManasteelAxe(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANASTEEL_AXE);
	public static final Item manasteelSword = new ItemManasteelSword(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANASTEEL_SWORD);
	public static final Item manasteelShears = new ItemManasteelShears(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANASTEEL_SHEARS);
	public static final Item terrasteelHelm = new ItemTerrasteelHelm(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TERRASTEEL_HELM);
	public static final Item terrasteelHelmRevealing = new ItemTerrasteelHelmRevealing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TERRASTEEL_HELM_R);
	public static final Item terrasteelChest = new ItemTerrasteelArmor(EntityEquipmentSlot.CHEST, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TERRASTEEL_CHEST);
	public static final Item terrasteelLegs = new ItemTerrasteelArmor(EntityEquipmentSlot.LEGS, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TERRASTEEL_LEGS);
	public static final Item terrasteelBoots = new ItemTerrasteelArmor(EntityEquipmentSlot.FEET, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TERRASTEEL_BOOTS);
	public static final Item terraSword = new ItemTerraSword(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TERRA_SWORD);
	public static final Item tinyPlanet = new ItemTinyPlanet(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TINY_PLANET);
	public static final Item manaRing = new ItemManaRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RING);
	public static final Item auraRing = new ItemAuraRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.AURA_RING);
	public static final Item manaRingGreater = new ItemGreaterManaRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_RING_GREATER);
	public static final Item auraRingGreater = new ItemGreaterAuraRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.AURA_RING_GREATER);
	public static final Item travelBelt = new ItemTravelBelt(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TRAVEL_BELT);
	public static final Item knockbackBelt = new ItemKnockbackBelt(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.KNOCKBACK_BELT);
	public static final Item icePendant = new ItemIcePendant(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ICE_PENDANT);
	public static final Item lavaPendant = new ItemLavaPendant(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.LAVA_PENDANT);
	public static final Item magnetRing = new ItemMagnetRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MAGNET_RING);
	public static final Item waterRing = new ItemWaterRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.WATER_RING);
	public static final Item miningRing = new ItemMiningRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MINING_RING);
	public static final Item terraPick = new ItemTerraPick(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TERRA_PICK);
	public static final Item divaCharm = new ItemDivaCharm(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.DIVA_CHARM);
	public static final Item flightTiara = new ItemFlightTiara(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.FLIGHT_TIARA);
	public static final Item enderDagger = new ItemEnderDagger(unstackable().defaultMaxDamage(69).setNoRepair()); // What you looking at?
	public static final Item darkQuartz = new ItemMod(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.QUARTZ_NAMES[0]);
	public static final Item manaQuartz = new ItemMod(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.QUARTZ_NAMES[1]);
	public static final Item blazeQuartz = new ItemMod(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.QUARTZ_NAMES[2]);
	public static final Item lavenderQuartz = new ItemMod(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.QUARTZ_NAMES[3]);
	public static final Item redQuartz = new ItemMod(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.QUARTZ_NAMES[4]);
	public static final Item elfQuartz = new ItemMod(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.QUARTZ_NAMES[5]);
	public static final Item sunnyQuartz = new ItemMod(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.QUARTZ_NAMES[6]);
	public static final Item waterRod = new ItemWaterRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.WATER_ROD);
	public static final Item elementiumHelm = new ItemElementiumHelm(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ELEMENTIUM_HELM);
	public static final Item elementiumHelmRevealing = new ItemElementiumHelmRevealing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ELEMENTIUM_HELM_R);
	public static final Item elementiumChest = new ItemElementiumChest(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ELEMENTIUM_CHEST);
	public static final Item elementiumLegs = new ItemElementiumLegs(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ELEMENTIUM_LEGS);
	public static final Item elementiumBoots = new ItemElementiumBoots(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ELEMENTIUM_BOOTS);
	public static final Item elementiumPick = new ItemElementiumPick(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ELEMENTIUM_PICK);
	public static final Item elementiumShovel = new ItemElementiumShovel(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ELEMENTIUM_SHOVEL);
	public static final Item elementiumAxe = new ItemElementiumAxe(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ELEMENTIUM_AXE);
	public static final Item elementiumSword = new ItemElementiumSword(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ELEMENTIUM_SWORD);
	public static final Item elementiumShears = new ItemElementiumShears(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ELEMENTIUM_SHEARS);
	public static final Item openBucket = new ItemOpenBucket(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.OPEN_BUCKET);
	public static final Item spawnerMover = new ItemSpawnerMover(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SPAWNER_MOVER);
	public static final Item pixieRing = new ItemPixieRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.PIXIE_RING);
	public static final Item superTravelBelt = new ItemSuperTravelBelt(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SUPER_TRAVEL_BELT);
	public static final Item rainbowRod = new ItemRainbowRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RAINBOW_ROD);
	public static final Item tornadoRod = new ItemTornadoRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TORNADO_ROD);
	public static final Item fireRod = new ItemFireRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.FIRE_ROD);
	public static final Item vineBall = new ItemVineBall(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.VINE_BALL);
	public static final Item slingshot = new ItemSlingshot(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SLINGSHOT);
	public static final Item manaBottle = new ItemBottledMana(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_BOTTLE);
	public static final Item laputaShard = new ItemLaputaShard(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.LAPUTA_SHARD);
	public static final Item necroVirus = new ItemVirus(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.NECRO_VIRUS);
	public static final Item nullVirus = new ItemVirus(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.NULL_VIRUS);
	public static final Item reachRing = new ItemReachRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.REACH_RING);
	public static final Item skyDirtRod = new ItemSkyDirtRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SKY_DIRT_ROD);
	public static final Item itemFinder = new ItemItemFinder(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ITEM_FINDER);
	public static final Item superLavaPendant = new ItemSuperLavaPendant(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SUPER_LAVA_PENDANT);
	public static final Item enderHand = new ItemEnderHand(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ENDER_HAND);
	public static final Item glassPick = new ItemGlassPick(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.GLASS_PICK);
	public static final Item spark = new ItemSpark(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SPARK);
	public static final Item sparkUpgradeDispersive = new ItemSparkUpgrade(defaultBuilder(), SparkUpgradeType.DISPERSIVE).setRegistryName(LibMisc.MOD_ID, LibItemNames.SPARK_UPGRADE + "_" + SparkUpgradeType.DISPERSIVE.name().toLowerCase(Locale.ROOT));
	public static final Item sparkUpgradeDominant = new ItemSparkUpgrade(defaultBuilder(), SparkUpgradeType.DOMINANT).setRegistryName(LibMisc.MOD_ID, LibItemNames.SPARK_UPGRADE + "_" + SparkUpgradeType.DOMINANT.name().toLowerCase(Locale.ROOT));
	public static final Item sparkUpgradeRecessive = new ItemSparkUpgrade(defaultBuilder(), SparkUpgradeType.RECESSIVE).setRegistryName(LibMisc.MOD_ID, LibItemNames.SPARK_UPGRADE + "_" + SparkUpgradeType.RECESSIVE.name().toLowerCase(Locale.ROOT));
	public static final Item sparkUpgradeIsolated = new ItemSparkUpgrade(defaultBuilder(), SparkUpgradeType.ISOLATED).setRegistryName(LibMisc.MOD_ID, LibItemNames.SPARK_UPGRADE + "_" + SparkUpgradeType.ISOLATED.name().toLowerCase(Locale.ROOT));
	public static final Item diviningRod = new ItemDiviningRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.DIVINING_ROD);
	public static final Item gravityRod = new ItemGravityRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.GRAVITY_ROD);
	public static final Item manaInkwell = new ItemManaInkwell(unstackable().setNoRepair()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANA_INKWELL);
	public static final Item vial = new ItemVial(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.VIAL);
	public static final Item flask = new ItemVial(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.FLASK);
	public static final Item brewVial = new ItemBrewBase(unstackable(), 4, 32, new ItemStack(vial)).setRegistryName(LibMisc.MOD_ID, LibItemNames.BREW_VIAL);
	public static final Item brewFlask = new ItemBrewBase(unstackable(), 6, 24, new ItemStack(flask)).setRegistryName(LibMisc.MOD_ID, LibItemNames.BREW_FLASK);
	public static final Item bloodPendant = new ItemBloodPendant(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.BLOOD_PENDANT);
	public static final Item missileRod = new ItemMissileRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MISSILE_ROD);
	public static final Item holyCloak = new ItemHolyCloak(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.HOLY_CLOAK);
	public static final Item unholyCloak = new ItemUnholyCloak(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.UNHOLY_CLOAK);
	public static final Item balanceCloak = new ItemBalanceCloak(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.BALANCE_CLOAK);
	public static final Item craftingHalo = new ItemCraftingHalo(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CRAFTING_HALO);
	public static final Item blackLotus = new ItemBlackLotus(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.BLACK_LOTUS);
	public static final Item blackerLotus = new ItemBlackLotus(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.BLACKER_LOTUS);
	public static final Item monocle = new ItemMonocle(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MONOCLE);
	public static final Item clip = new ItemMod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CLIP);
	public static final Item cobbleRod = new ItemCobbleRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.COBBLE_ROD);
	public static final Item smeltRod = new ItemSmeltRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SMELT_ROD);
	public static final Item worldSeed = new ItemWorldSeed(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.WORLD_SEED);
	public static final Item spellCloth = new ItemSpellCloth(unstackable().defaultMaxDamage(35).setNoRepair()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SPELL_CLOTH);
	public static final Item thornChakram = new ItemThornChakram(defaultBuilder().maxStackSize(6)).setRegistryName(LibMisc.MOD_ID, LibItemNames.THORN_CHAKRAM);
	public static final Item flareChakram = new ItemThornChakram(defaultBuilder().maxStackSize(6)).setRegistryName(LibMisc.MOD_ID, LibItemNames.FLARE_CHAKRAM);
	public static final Item overgrowthSeed = new ItemOvergrowthSeed(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.OVERGROWTH_SEED);
	public static final Item craftPattern1_1 = new ItemCraftPattern(CratePattern.CRAFTY_1_1, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CRAFT_PATTERN_PREFIX + "1_1");
	public static final Item craftPattern2_2 = new ItemCraftPattern(CratePattern.CRAFTY_2_2, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CRAFT_PATTERN_PREFIX + "2_2");
	public static final Item craftPattern1_2 = new ItemCraftPattern(CratePattern.CRAFTY_1_2, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CRAFT_PATTERN_PREFIX + "1_2");
	public static final Item craftPattern2_1 = new ItemCraftPattern(CratePattern.CRAFTY_2_1, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CRAFT_PATTERN_PREFIX + "2_1");
	public static final Item craftPattern1_3 = new ItemCraftPattern(CratePattern.CRAFTY_1_3, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CRAFT_PATTERN_PREFIX + "1_3");
	public static final Item craftPattern3_1 = new ItemCraftPattern(CratePattern.CRAFTY_3_1, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CRAFT_PATTERN_PREFIX + "3_1");
	public static final Item craftPattern2_3 = new ItemCraftPattern(CratePattern.CRAFTY_2_3, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CRAFT_PATTERN_PREFIX + "2_3");
	public static final Item craftPattern3_2 = new ItemCraftPattern(CratePattern.CRAFTY_3_2, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CRAFT_PATTERN_PREFIX + "3_2");
	public static final Item craftPatternDonut = new ItemCraftPattern(CratePattern.CRAFTY_DONUT, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CRAFT_PATTERN_PREFIX + "donut");
	public static final Item ancientWillAhrim = new ItemAncientWill(IAncientWillContainer.AncientWillType.AHRIM, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ANCIENT_WILL_PREFIX + "ahrim");
	public static final Item ancientWillDharok = new ItemAncientWill(IAncientWillContainer.AncientWillType.DHAROK, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ANCIENT_WILL_PREFIX + "dharok");
	public static final Item ancientWillGuthan = new ItemAncientWill(IAncientWillContainer.AncientWillType.GUTHAN, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ANCIENT_WILL_PREFIX + "guthan");
	public static final Item ancientWillTorag = new ItemAncientWill(IAncientWillContainer.AncientWillType.TORAG, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ANCIENT_WILL_PREFIX + "torag");
	public static final Item ancientWillVerac = new ItemAncientWill(IAncientWillContainer.AncientWillType.VERAC, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ANCIENT_WILL_PREFIX + "verac");
	public static final Item ancientWillKaril = new ItemAncientWill(IAncientWillContainer.AncientWillType.KARIL, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ANCIENT_WILL_PREFIX + "karil");
	public static final Item corporeaSpark = new ItemCorporeaSpark(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CORPOREA_SPARK);
	public static final Item corporeaSparkMaster = new ItemCorporeaSpark(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CORPOREA_SPARK_MASTER);
	public static final Item livingwoodBow = new ItemLivingwoodBow(defaultBuilder().defaultMaxDamage(500)).setRegistryName(LibMisc.MOD_ID, LibItemNames.LIVINGWOOD_BOW);
	public static final Item crystalBow = new ItemCrystalBow(defaultBuilder().defaultMaxDamage(500)).setRegistryName(LibMisc.MOD_ID, LibItemNames.CRYSTAL_BOW);
	public static final Map<ItemBaubleCosmetic.Variant, Item> cosmetics = new EnumMap<>(ItemBaubleCosmetic.Variant.class);
	static {
		for(ItemBaubleCosmetic.Variant v : ItemBaubleCosmetic.Variant.values()) {
			cosmetics.put(v, new ItemBaubleCosmetic(v, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.COSMETIC_PREFIX + v.name().toLowerCase(Locale.ROOT)));
		}
	}
	public static final Item swapRing = new ItemSwapRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SWAP_RING);
	public static final Item flowerBag = new ItemFlowerBag(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.FLOWER_BAG);
	public static final Item phantomInk = new ItemMod(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.PHANTOM_INK);
	public static final Item poolMinecart = new ItemPoolMinecart(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.POOL_MINECART);
	public static final Item pinkinator = new ItemPinkinator(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.PINKINATOR);
	public static final Item infiniteFruit = new ItemInfiniteFruit(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.INFINITE_FRUIT);
	public static final Item kingKey = new ItemKingKey(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.KING_KEY);
	public static final Item flugelEye = new ItemFlugelEye(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.FLUGEL_EYE);
	public static final Item thorRing = new ItemThorRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.THOR_RING);
	public static final Item odinRing = new ItemOdinRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ODIN_RING);
	public static final Item lokiRing = new ItemLokiRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.LOKI_RING);
	public static final Item dice = new ItemDice(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.DICE);
	public static final Item keepIvy = new ItemKeepIvy(defaultBuilder()).setRegistryName(LibMisc.MOD_ID, LibItemNames.KEEP_IVY);
	public static final Item blackHoleTalisman = new ItemBlackHoleTalisman(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.BLACK_HOLE_TALISMAN);
	public static final Item recordGaia1 = new ItemModRecord(1, ModSounds.gaiaMusic1, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RECORD_GAIA1);
	public static final Item recordGaia2 = new ItemModRecord(1, ModSounds.gaiaMusic2, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.RECORD_GAIA2);
	public static final Item temperanceStone = new ItemTemperanceStone(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TEMPERANCE_STONE);
	public static final Item incenseStick = new ItemIncenseStick(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.INCENSE_STICK);
	public static final Item terraAxe = new ItemTerraAxe(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.TERRA_AXE);
	public static final Item waterBowl = new ItemWaterBowl(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.WATER_BOWL);
	public static final Item obedienceStick = new ItemObedienceStick(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.OBEDIENCE_STICK);
	public static final Item cacophonium = new ItemCacophonium(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CACOPHONIUM);
	public static final Item slimeBottle = new ItemSlimeBottle(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SLIME_BOTTLE);
	public static final Item starSword = new ItemStarSword(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.STAR_SWORD);
	public static final Item exchangeRod = new ItemExchangeRod(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.EXCHANGE_ROD);
	public static final Item magnetRingGreater = new ItemGreaterMagnetRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MAGNET_RING_GREATER);
	public static final Item thunderSword = new ItemThunderSword(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.THUNDER_SWORD);
	public static final Item manaweaveHelm = new ItemManaweaveHelm(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANAWEAVE_HELM);
	public static final Item manaweaveChest = new ItemManaweaveArmor(EntityEquipmentSlot.CHEST, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANAWEAVE_CHEST);
	public static final Item manaweaveLegs = new ItemManaweaveArmor(EntityEquipmentSlot.LEGS, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANAWEAVE_LEGS);
	public static final Item manaweaveBoots = new ItemManaweaveArmor(EntityEquipmentSlot.FEET, unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.MANAWEAVE_BOOTS);
	public static final Item autocraftingHalo = new ItemAutocraftingHalo(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.AUTOCRAFTING_HALO);
	public static final Item gaiaHead = new ItemGaiaHead();
	public static final Item sextant = new ItemSextant(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SEXTANT);
	public static final Item speedUpBelt = new ItemSpeedUpBelt(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SPEED_UP_BELT);
	public static final Item baubleBox = new ItemBaubleBox(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.BAUBLE_BOX);
	public static final Item dodgeRing = new ItemDodgeRing(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.DODGE_RING);
	public static final Item invisibilityCloak = new ItemInvisibilityCloak(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.INVISIBILITY_CLOAK);
	public static final Item cloudPendant = new ItemCloudPendant(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.CLOUD_PENDANT);
	public static final Item superCloudPendant = new ItemSuperCloudPendant(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.SUPER_CLOUD_PENDANT);
	public static final Item thirdEye = new ItemThirdEye(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.THIRD_EYE);
	public static final Item astrolabe = new ItemAstrolabe(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.ASTROLABE);
	public static final Item goddessCharm = new ItemGoddessCharm(unstackable()).setRegistryName(LibMisc.MOD_ID, LibItemNames.GODDESS_CHARM);

	public static Item.Properties defaultBuilder() {
		return new Item.Properties().group(BotaniaCreativeTab.INSTANCE);
	}

	private static Item.Properties unstackable() {
		return defaultBuilder().maxStackSize(1);
	}

	@SubscribeEvent
	public static void registerItems(RegistryEvent.Register<Item> evt) {
		IForgeRegistry<Item> r = evt.getRegistry();

		r.register(lexicon);
		petals.values().forEach(r::register);
		dyes.values().forEach(r::register);
		r.register(pestleAndMortar);
		r.register(twigWand);
		r.register(manaSteel);
		r.register(manaPearl);
		r.register(manaDiamond);
		r.register(livingwoodTwig);
		r.register(terrasteel);
		r.register(lifeEssence);
		r.register(redstoneRoot);
		r.register(elementium);
		r.register(pixieDust);
		r.register(dragonstone);
		r.register(placeholder);
		r.register(redString);
		r.register(dreamwoodTwig);
		r.register(gaiaIngot);
		r.register(enderAirBottle);
		r.register(manaString);
		r.register(manasteelNugget);
		r.register(terrasteelNugget);
		r.register(elementiumNugget);
		r.register(livingroot);
		r.register(pebble);
		r.register(manaweaveCloth);
		r.register(manaPowder);
		r.register(lensNormal);
		r.register(lensSpeed);
		r.register(lensPower);
		r.register(lensTime);
		r.register(lensEfficiency);
		r.register(lensBounce);
		r.register(lensGravity);
		r.register(lensMine);
		r.register(lensDamage);
		r.register(lensPhantom);
		r.register(lensMagnet);
		r.register(lensExplosive);
		r.register(lensInfluence);
		r.register(lensWeight);
		r.register(lensPaint);
		r.register(lensFire);
		r.register(lensPiston);
		r.register(lensLight);
		r.register(lensWarp);
		r.register(lensRedirect);
		r.register(lensFirework);
		r.register(lensFlare);
		r.register(lensMessenger);
		r.register(lensTripwire);
		r.register(lensStorm);
		r.register(runeWater);
		r.register(runeFire);
		r.register(runeEarth);
		r.register(runeAir);
		r.register(runeSpring);
		r.register(runeSummer);
		r.register(runeAutumn);
		r.register(runeWinter);
		r.register(runeMana);
		r.register(runeLust);
		r.register(runeGluttony);
		r.register(runeGreed);
		r.register(runeSloth);
		r.register(runeWrath);
		r.register(runeEnvy);
		r.register(runePride);
		r.register(manaTablet);
		r.register(manaGun);
		r.register(manaCookie);
		r.register(fertilizer);
		r.register(grassSeeds);
		r.register(podzolSeeds);
		r.register(mycelSeeds);
		r.register(drySeeds);
		r.register(goldenSeeds);
		r.register(vividSeeds);
		r.register(scorchedSeeds);
		r.register(infusedSeeds);
		r.register(mutatedSeeds);
		r.register(dirtRod);
		r.register(terraformRod);
		r.register(grassHorn);
		r.register(leavesHorn);
		r.register(snowHorn);
		r.register(manaMirror);
		r.register(manasteelHelm);
		r.register(manasteelHelmRevealing);
		r.register(manasteelChest);
		r.register(manasteelLegs);
		r.register(manasteelBoots);
		r.register(manasteelPick);
		r.register(manasteelShovel);
		r.register(manasteelAxe);
		r.register(manasteelSword);
		r.register(manasteelShears);
		r.register(terrasteelHelm);
		r.register(terrasteelHelmRevealing);
		r.register(terrasteelChest);
		r.register(terrasteelLegs);
		r.register(terrasteelBoots);
		r.register(terraSword);
		r.register(tinyPlanet);
		r.register(manaRing);
		r.register(auraRing);
		r.register(manaRingGreater);
		r.register(auraRingGreater);
		r.register(travelBelt);
		r.register(knockbackBelt);
		r.register(icePendant);
		r.register(lavaPendant);
		r.register(magnetRing);
		r.register(waterRing);
		r.register(miningRing);
		r.register(terraPick);
		r.register(divaCharm);
		r.register(flightTiara);
		r.register(enderDagger);
		r.register(darkQuartz);
		r.register(manaQuartz);
		r.register(blazeQuartz);
		r.register(lavenderQuartz);
		r.register(redQuartz);
		r.register(elfQuartz);
		r.register(sunnyQuartz);
		r.register(waterRod);
		r.register(elementiumHelm);
		r.register(elementiumHelmRevealing);
		r.register(elementiumChest);
		r.register(elementiumLegs);
		r.register(elementiumBoots);
		r.register(elementiumPick);
		r.register(elementiumShovel);
		r.register(elementiumAxe);
		r.register(elementiumSword);
		r.register(elementiumShears);
		r.register(openBucket);
		r.register(spawnerMover);
		r.register(pixieRing);
		r.register(superTravelBelt);
		r.register(rainbowRod);
		r.register(tornadoRod);
		r.register(fireRod);
		r.register(vineBall);
		r.register(slingshot);
		r.register(manaBottle);
		r.register(laputaShard);
		r.register(necroVirus);
		r.register(nullVirus);
		r.register(reachRing);
		r.register(skyDirtRod);
		r.register(itemFinder);
		r.register(superLavaPendant);
		r.register(enderHand);
		r.register(glassPick);
		r.register(spark);
		r.register(sparkUpgradeDispersive);
		r.register(sparkUpgradeDominant);
		r.register(sparkUpgradeRecessive);
		r.register(sparkUpgradeIsolated);
		r.register(diviningRod);
		r.register(gravityRod);
		r.register(manaInkwell);
		r.register(vial);
		r.register(flask);
		r.register(brewVial);
		r.register(brewFlask);
		r.register(bloodPendant);
		r.register(missileRod);
		r.register(holyCloak);
		r.register(unholyCloak);
		r.register(balanceCloak);
		r.register(craftingHalo);
		r.register(blackLotus);
		r.register(blackerLotus);
		r.register(monocle);
		r.register(clip);
		r.register(cobbleRod);
		r.register(smeltRod);
		r.register(worldSeed);
		r.register(spellCloth);
		r.register(thornChakram);
		r.register(flareChakram);
		r.register(overgrowthSeed);
		r.register(craftPattern1_1);
		r.register(craftPattern2_2);
		r.register(craftPattern1_2);
		r.register(craftPattern2_1);
		r.register(craftPattern1_3);
		r.register(craftPattern3_1);
		r.register(craftPattern2_3);
		r.register(craftPattern3_2);
		r.register(craftPatternDonut);
		r.register(ancientWillAhrim);
		r.register(ancientWillDharok);
		r.register(ancientWillGuthan);
		r.register(ancientWillTorag);
		r.register(ancientWillVerac);
		r.register(ancientWillKaril);
		r.register(corporeaSpark);
		r.register(corporeaSparkMaster);
		r.register(livingwoodBow);
		r.register(crystalBow);
		cosmetics.values().forEach(r::register);
		r.register(swapRing);
		r.register(flowerBag);
		r.register(phantomInk);
		r.register(poolMinecart);
		r.register(pinkinator);
		r.register(infiniteFruit);
		r.register(kingKey);
		r.register(flugelEye);
		r.register(thorRing);
		r.register(odinRing);
		r.register(lokiRing);
		r.register(dice);
		r.register(keepIvy);
		r.register(blackHoleTalisman);
		r.register(recordGaia1);
		r.register(recordGaia2);
		r.register(temperanceStone);
		r.register(incenseStick);
		r.register(terraAxe);
		r.register(waterBowl);
		r.register(obedienceStick);
		r.register(cacophonium);
		r.register(slimeBottle);
		r.register(starSword);
		r.register(exchangeRod);
		r.register(magnetRingGreater);
		r.register(thunderSword);
		r.register(manaweaveHelm);
		r.register(manaweaveChest);
		r.register(manaweaveLegs);
		r.register(manaweaveBoots);
		r.register(autocraftingHalo);
		r.register(gaiaHead);
		r.register(sextant);
		r.register(speedUpBelt);
		r.register(baubleBox);
		r.register(dodgeRing);
		r.register(invisibilityCloak);
		r.register(cloudPendant);
		r.register(superCloudPendant);
		r.register(thirdEye);
		r.register(astrolabe);
		r.register(goddessCharm);

		registerOreDictionary();
	}
	
	private static void registerOreDictionary() {
		OreDictionary.registerOre(LibOreDict.LEXICON, lexicon);
		for(EnumDyeColor color : EnumDyeColor.values()) {
			OreDictionary.registerOre(LibOreDict.PETAL[color.getMetadata()], new ItemStack(petals.get(color)));
			OreDictionary.registerOre(LibOreDict.DYE[color.getMetadata()], new ItemStack(dyes.get(color)));
			OreDictionary.registerOre(LibOreDict.DYE_WILDCARD, new ItemStack(dyes.get(color)));
		}

		OreDictionary.registerOre(LibOreDict.RUNE[0], new ItemStack(runeWater));
		OreDictionary.registerOre(LibOreDict.RUNE[1], new ItemStack(runeFire));
		OreDictionary.registerOre(LibOreDict.RUNE[2], new ItemStack(runeEarth));
		OreDictionary.registerOre(LibOreDict.RUNE[3], new ItemStack(runeAir));
		OreDictionary.registerOre(LibOreDict.RUNE[4], new ItemStack(runeSpring));
		OreDictionary.registerOre(LibOreDict.RUNE[5], new ItemStack(runeSummer));
		OreDictionary.registerOre(LibOreDict.RUNE[6], new ItemStack(runeAutumn));
		OreDictionary.registerOre(LibOreDict.RUNE[7], new ItemStack(runeWinter));
		OreDictionary.registerOre(LibOreDict.RUNE[8], new ItemStack(runeMana));
		OreDictionary.registerOre(LibOreDict.RUNE[9], new ItemStack(runeLust));
		OreDictionary.registerOre(LibOreDict.RUNE[10], new ItemStack(runeGluttony));
		OreDictionary.registerOre(LibOreDict.RUNE[11], new ItemStack(runeGreed));
		OreDictionary.registerOre(LibOreDict.RUNE[12], new ItemStack(runeSloth));
		OreDictionary.registerOre(LibOreDict.RUNE[13], new ItemStack(runeWrath));
		OreDictionary.registerOre(LibOreDict.RUNE[14], new ItemStack(runeEnvy));
		OreDictionary.registerOre(LibOreDict.RUNE[15], new ItemStack(runePride));

		OreDictionary.registerOre(LibOreDict.QUARTZ[0], new ItemStack(darkQuartz));
		OreDictionary.registerOre(LibOreDict.QUARTZ[1], new ItemStack(manaQuartz));
		OreDictionary.registerOre(LibOreDict.QUARTZ[2], new ItemStack(blazeQuartz));
		OreDictionary.registerOre(LibOreDict.QUARTZ[3], new ItemStack(lavenderQuartz));
		OreDictionary.registerOre(LibOreDict.QUARTZ[4], new ItemStack(redQuartz));
		OreDictionary.registerOre(LibOreDict.QUARTZ[5], new ItemStack(elfQuartz));
		OreDictionary.registerOre(LibOreDict.QUARTZ[6], new ItemStack(sunnyQuartz));

		OreDictionary.registerOre(LibOreDict.PESTLE_AND_MORTAR, pestleAndMortar);
		OreDictionary.registerOre(LibOreDict.MANA_STEEL, new ItemStack(manaSteel));
		OreDictionary.registerOre(LibOreDict.MANA_PEARL, new ItemStack(manaPearl));
		OreDictionary.registerOre(LibOreDict.MANA_DIAMOND, new ItemStack(manaDiamond));
		OreDictionary.registerOre(LibOreDict.LIVINGWOOD_TWIG, new ItemStack(livingwoodTwig));
		OreDictionary.registerOre(LibOreDict.TERRA_STEEL, new ItemStack(terrasteel));
		OreDictionary.registerOre(LibOreDict.LIFE_ESSENCE, new ItemStack(lifeEssence));
		OreDictionary.registerOre(LibOreDict.REDSTONE_ROOT, new ItemStack(redstoneRoot));
		OreDictionary.registerOre(LibOreDict.ELEMENTIUM, new ItemStack(elementium));
		OreDictionary.registerOre(LibOreDict.PIXIE_DUST, new ItemStack(pixieDust));
		OreDictionary.registerOre(LibOreDict.DRAGONSTONE, new ItemStack(dragonstone));
		OreDictionary.registerOre(LibOreDict.PLACEHOLDER, new ItemStack(placeholder));
		OreDictionary.registerOre(LibOreDict.RED_STRING, new ItemStack(redString));
		OreDictionary.registerOre(LibOreDict.DREAMWOOD_TWIG, new ItemStack(dreamwoodTwig));
		OreDictionary.registerOre(LibOreDict.GAIA_INGOT, new ItemStack(gaiaIngot));
		OreDictionary.registerOre(LibOreDict.ENDER_AIR_BOTTLE, new ItemStack(enderAirBottle));
		OreDictionary.registerOre(LibOreDict.MANA_STRING, new ItemStack(manaString));
		OreDictionary.registerOre(LibOreDict.MANASTEEL_NUGGET, new ItemStack(manasteelNugget));
		OreDictionary.registerOre(LibOreDict.TERRASTEEL_NUGGET, new ItemStack(terrasteelNugget));
		OreDictionary.registerOre(LibOreDict.ELEMENTIUM_NUGGET, new ItemStack(elementiumNugget));
		OreDictionary.registerOre(LibOreDict.ROOT, new ItemStack(livingroot));
		OreDictionary.registerOre(LibOreDict.PEBBLE, new ItemStack(pebble));
		OreDictionary.registerOre(LibOreDict.MANAWEAVE_CLOTH, new ItemStack(manaweaveCloth));
		OreDictionary.registerOre(LibOreDict.MANA_POWDER, new ItemStack(manaPowder));

		OreDictionary.registerOre(LibOreDict.VIAL, new ItemStack(vial));
		OreDictionary.registerOre(LibOreDict.FLASK, new ItemStack(flask));

		BotaniaAPI.blackListItemFromLoonium(lexicon);
		BotaniaAPI.blackListItemFromLoonium(overgrowthSeed);
		BotaniaAPI.blackListItemFromLoonium(blackLotus);
		BotaniaAPI.blackListItemFromLoonium(blackerLotus);
		for(Item i : Item.REGISTRY) {
			if("minecraft".equals(i.getRegistryName().getNamespace()) & i instanceof ItemRecord) {
				BotaniaAPI.blackListItemFromLoonium(i);
			}
		}

		OreDictionary.registerOre("rodBlaze", Items.BLAZE_ROD);
		OreDictionary.registerOre("powderBlaze", Items.BLAZE_POWDER);
	}
}
