blank_issues_enabled: false
contact_links:
  - name: Violet Moon Discord
    url: https://discord.gg/vm
    about: Join our Discord for support, questions, discussion.
  - name: Botania Forums
    url: https://forum.violetmoon.org/t/botania
    about: Visit the Botania forum for suggestions.
