plugins {
    id("multiloader-loader")
    id("net.neoforged.moddev")
}

repositories {
    maven {
        name = "C4"
        url = "https://maven.theillusivec4.top/"
    }
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(":Xplat").file("src/main/resources/META-INF/accesstransformer.cfg")
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty("neoforge.enabledGameTestNamespaces", mod_id)
            systemProperty("fml.earlyprogresswindow", "false")
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
            gameDirectory = file("../run/")
        }

        client {
            client()
            systemProperty("neoforge.logging.console.level", "debug")
        }
        neoforgeDatagen {
            data()
            programArguments.addAll("--mod", mod_id, "--all",
                    "--output", file("src/generated/resources/").getAbsolutePath(),
                    "--existing", file("src/main/resources/").getAbsolutePath())
        }
        gardenOfGlassDatagen {
            data()
            programArguments.addAll("--mod", mod_id, "--all",
                    "--output", file("../garden_of_glass/src/generated/resources/").getAbsolutePath(),
                    "--existing", file("../garden_of_glass/src/main/resources/").getAbsolutePath())
            systemProperty("botania.gog_datagen", "1")
        }
        server {
            server()
            systemProperty("neoforge.logging.console.level", "debug")
            programArgument("--nogui")
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    implementation("vazkii.patchouli:Patchouli:${patchouli_version}-NEOFORGE")
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    compileOnly("dev.emi:emi-neoforge:${emi_version}:api")
    //runtimeOnly("dev.emi:emi-neoforge:${emi_version}")

    compileOnly("me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}")
    //runtimeOnly("me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}")

    compileOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}:api")
    runtimeOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}")

    compileOnly("com.unascribed:ears-api:${ears_version}")

    compileOnly("maven.modrinth:sodium:mc${minecraft_version}-${sodium_version}-neoforge") { transitive = false }

    compileOnly("maven.modrinth:embeddium:${embeddium_version}+mc${minecraft_version}") { transitive = false }

    compileOnly("org.jetbrains:annotations:26.0.2")

    if (file("../garden_of_glass/gardenofglass-${gog_version}.jar").exists()) {
        runtimeOnly(files("../garden_of_glass/gardenofglass-${gog_version}.jar"))
    }
}
